### ISSUE TITLE
Pit tag row numbers between field notes and reader csv export not aligned

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#1]
See https://github.com/NewGraphEnvironment/dff-2022/issues/44

As per the last entry

 - Looking at the times of the pit_tag file generated from

[dff-2022/scripts/pit_tags.R](https://github.com/NewGraphEnvironment/dff-2022/blob/066c382b2eef2517dfe1d35df2d0bd3a73fd230d/scripts/pit_tags.R#L13)

Line 13 in [066c382](https://github.com/NewGraphEnvironment/dff-2022/commit/066c382b2eef2517dfe1d35df2d0bd3a73fd230d)

 pit_tag <- readr::read_csv(path) %>% 
they look like those first two fish from the Missinka site. If that is the case then the numbers in the fish dataframe would all be off by one. To remedyis  that we would have needed to add 1 to the row_id numbering in the pit_tag sheet for it to match.

**Comment by NewGraphEnvironment** [comment]
Since this is already done we probably just leave it but for reference the way to fix it is perhaps  to mutate the row ID column of the fish day frame by subtracting one before joining

**Comment by Mateo9569** [comment]
You were right, when I imported the tag data for skeena I subtracted one from tag_row column in fish_data.csv and that did the trick. I had to do this by hand though because I needed the paper cards to find out which fish got a tag and which didn't. Hope that makes sense.
