### ISSUE TITLE
build and sub in the static overview map into background section

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#10]
Use the updated `fishpassage_skeena_2022` map on mergin, be sure to sync changes from generating Bulkley map before beginning

- [ ] duplicate composer of map used for bulkley 2022, 
- [ ] use watershed group layer already good to go for bulk, morr, kisp and zymo (leave bulk in there even though no sites in there yet)
- [ ] name `png` output the same as bulkley and save direct from mergin to this repo `fig` file.  
- [ ] use export `png` resolution of 200px so not a huge file
- [ ] Lock out layers and styles in `map` object in composer when done so map won't change when map view changed.
- [ ] sync to mergin when draft completed

**Comment by Mateo9569** [comment]
I'm confused, I'm doing this for the Parsnip watershed, right? Wouldn't it be easier to start a new mergin project? And bring over the basemap layers I need, and name the png for the parsnip

**Comment by NewGraphEnvironment** [comment]
Oh crap. I put this in the wrong repo!  will close and link in Skeena
