### ISSUE TITLE
Runtime exception error occurs when attempting to build pdf

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#104]
```
rmarkdown::render_site(output_format = 'pagedown::html_paged',
                         encoding = 'UTF-8')
```
Running the above line works, no errors in console. When opening `Peace2022.html` in my web browser, everything seems to be there. However the webpage just goes blank after 5 seconds. Also there is code on the webpage in a few spots.
![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/99455166/dadc0020-81cc-4a5a-a26a-101be1a65146)

```
 pagedown::chrome_print(
    paste0(getwd(), '/', filename_html, '.html'),
    output = paste0(getwd(),'/docs/', filename_html, '.pdf'),
    timeout = 180
  )
```
Running the above chunk does not work at all. And a long error message appears in the console (seen below).
![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/99455166/1d68924c-1722-47d4-92d0-324bf0330bd3)

Latest session info (R version 4.2.2) : 
![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/99455166/6a48e739-8752-4bf7-90c3-b93ae5d79cd1)

**Comment by NewGraphEnvironment** [comment]
Saw this Saturday. I think it is because `gitbook_on` is not set to false and saved in the index file before you try to render.

The giveaway is that it is looking for URLs at maps made easy, but everywhere it is meant to look for those should be turned off when gitbook_on is set to false

**Comment by Mateo9569** [comment]
Wow, I feel silly now. Thanks so much. I do still get a runtime error after saving the index file. The pdf still builds though so I think we're good. 

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/99455166/4e5b6842-ae25-4ee9-a733-5b3c6b17a07c)

**Comment by NewGraphEnvironment** [comment]
ya - I always get those "runtime exception" errors too.  Been happening for years. seems harmless so far
