### ISSUE TITLE
duplicate PSCIS crossings

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#110]
![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/99455166/9e819053-e797-477b-8fc5-d05e7f106d65)

I believe these two pscis assessment points are the exact same crossing. But they were assessed at different times and have slightly different measurements. Both contain links to culvert photos, and it seems they are the same. Unless there are twin culverts at this site, seems unlikely.

**Comment by smnorris** [comment]
Report PSCIS errors for fixing here: https://github.com/smnorris/PSCIS_datafixes - I'll file this one.

**Comment by Mateo9569** [comment]
Thanks Simon! I can add it to https://github.com/smnorris/bcfishpass/blob/main/data/pscis_modelledcrossings_streams_xref.csv

**Comment by NewGraphEnvironment** [comment]
this one needs to be added https://github.com/smnorris/PSCIS_datafixes .  Al will do this

6824 / 6746
