### ISSUE TITLE
Put crossing 372413 from CRKD watershed back in phase 1 sheet and make note

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#12]
Needs to be pulled out of the template. This crossing is in the 'CRKD' watershed. It's a bridge that was assessed on the road before entering the parsnip watershed.

**Comment by NewGraphEnvironment** [comment]
Its ok to leave it in there. Its not in the Parsnip but our study area and Hillcrest maps cover that area. Really we can be anywhere that eventually flows through those dams.  I'd just put a wee note in the pscis spreadsheet comments that it is in the Crooked River watershed.  Todo bien
