### ISSUE TITLE
What was the distance surveyed upstream of crossing 125194 (Trib to Missinka)?

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#19]
This is kind of related to #18 but I figured I'd make a separate issue. There is no survey distance on your site card for 125194_us. Just wondering how I should measure this. Because you also walked to modelled crossing 16601526 (shown below on track), which is on the same system. I can see a couple pictures from that crossing and it's just a beaver dam. It looks like you left the stream and walked on the road for a while. I guess I just need some clarification on what to put for survey length, and let me know if the clipped track is accurate. I will include that modelled crossing in the memo. 

![image](https://user-images.githubusercontent.com/99455166/220755685-a0cf0deb-c8ce-4735-a6ef-34ee51427355.png)

**Comment by NewGraphEnvironment** [comment]
I would document upstream survey distance as to the last point on the stream before I walked back out to the road and then back in on the historic road to 1016601526.  I was on the road a tiny bit before too as it was very close to the stream and much much easier travelling.

Then in the text of the memo it can mention that I accessed that "ford"/beaverdam site to check for a structure and assess habitat at that location.  

Im sure you are on it but `track_lines` is the layer we are after for the mapping vs the `track_points` layer. I think perhaps the gpx file has both but I can't remember off the top of my head in what form it is packaged for mapping (added to the geopackage with a function then exported to an individual geojson for Simon I think....).
