### ISSUE TITLE
`tab_cost_rd_mult` object not present on `main` branch yet because it was ignored in `.gitignore`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#35]
This means I can not reproduce the build.

If we get stuck in this state (due to #31 or something else), we are going to have to either load this to the sqlite and pull out of there or find another way to share what is going on. I guess we could load the csv and I could load by hand into the `data/inputs_raw` directory

**Comment by Mateo9569** [comment]
I loaded the csv to `data/inputs_raw` directory from one of the other repos, I think it was from skeena 2022. Was that wrong, would the multipliers be different for parsnip? That directory isn't ignored, I think I forgot to commit that file in my last PR. I'll commit next time.

**Comment by NewGraphEnvironment** [comment]
file was ignored until after the last PR (when you ignored it explicitly).. lol

https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/pull/26/commits/27fd6b6b6d63c6ad4fc164cee7c9b0287f69d940
