### ISSUE TITLE
References - include all of title (Project # too)  for 2020 and 2022 parsnip reports. tags. formats

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#39]
1. its the name 
2.  will drastically improve search-ability

Parsnip River Watershed – Fish Habitat Confirmations (PEA-F20-F-2967)

**Comment by NewGraphEnvironment** [comment]
also include tags on all new references in shared zotero library

I need to learn how to cite Web Pages properly...  Is there a reason the BC Parks reference has 2020 as the year and no author? is our zotero input on this currently in a standard setup for this type of reference? If so we can put a link here to how to cite websites properly here in this issue for now

**Comment by Mateo9569** [comment]
Updated my comment above. Yes I can have a look. I can research and QA the references we have currently.
