### ISSUE TITLE
Fern pscis id not used for `16601271`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#42]
looks like it is now `198321`

imapbc / data sources/ add provincial layers / {search term barrier}

report text references the main fsr crossing ("There is a modelled crossing located 700m upstream of crossing `r as.character(my_site)`")

![image](https://user-images.githubusercontent.com/46538103/227960496-c2b65171-d1b5-4b6b-9818-cc56dcb39df4.png)

**Comment by Mateo9569** [comment]
Deactivated crossings such as that one are still ok to upload to the pscis database correct? They would be listed under "unknown"?
