### ISSUE TITLE
QA tool error in `habitat_confirmations.xls` due to empty sculpin stage field 

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#47]
Stage is a required field in the spreadsheet. However in script used to determine fish life stage, there is case when for sculpins (lines referenced [here](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/blob/62b46d6aaae4274a61607dd1436121c5fe9afdfa/scripts/01_prep_inputs/0100-extract-inputs.R#L868-L873)). QA tool error message says "Required field, if blank must explain in comments field". Even though there are comments saying "not salmonids so no life stage specified". Wondering if we should just put something in the stage field.

**Comment by NewGraphEnvironment** [comment]
Hmm.  perhaps lets just put adult and find replace comments to say "life stage not actually determined but populated to meet QA tool requirements" or something
