### ISSUE TITLE
tag Anzac trib upstream modelled crossing as not existing based on aerial imagery

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#74]
in `bcfishpass` repo

https://github.com/smnorris/bcfishpass/blob/main/data/user_modelled_crossing_fixes.csv

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/46538103/81b7b6c5-09c5-45ca-b9aa-a68be9f64217)

**Comment by Mateo9569** [comment]
@NewGraphEnvironment did you want to take a quick glance at my [commit](https://github.com/smnorris/bcfishpass/compare/main...Mateo9569:bcfishpass:crossing_fixes) before I submit PR to Simon?

**Comment by NewGraphEnvironment** [comment]
Should prob remove quotes for 125345 .  You could use your own initials since they are your words

Should add 1660987 too actually.   Crossing does not exist - field verified

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/46538103/7fb79a46-0eec-48c1-8177-4dd43fafbcd5)

**Comment by Mateo9569** [comment]
Done. I never added quotes, weird that github says they are there.
