### ISSUE TITLE
strange error message on build

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#82]
doesn't seem to be hurting anuything but I wonder what it is

```
Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) : 
  invalid first argument
Error in assign(cacheKey, frame, .rs.CachedDataEnv) : 
  attempt to use zero-length variable name
``

@Mateo9569 - do you get the same thing after running.  no rush as seems to be harmless

```
rmarkdown::render_site(output_format = 'bookdown::gitbook',
                       encoding = 'UTF-8')
```?

**Comment by Mateo9569** [comment]
No I have not gotten that error message after running

**Comment by Mateo9569** [comment]
This might help: https://github.com/rstudio/rstudio/issues/13188

**Comment by NewGraphEnvironment** [comment]
totally. i actually found that link then forgot! don't want to mess with any updates right before the report is due. Thanks!
