### ISSUE TITLE
update Table 1.1: Fish species recorded

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#84]
include columns for CARP and CRKD (example of how this could be done in past bulk/skeena and Elk reports)  and define BClist and Cosewic terms in footnotes

**Comment by NewGraphEnvironment** [comment]
have a good look at build script in peace and skeena repos.  skeena one might cross right over with very minor changes.  elk might be a bit odd because flathead isn't actually a different watershed group from elkr so not a good place to start.  

watch out for and test the pdf build too as sometimes it is too wide and messes up the pdf

**Comment by NewGraphEnvironment** [comment]
@Mateo9569 - make sure you update Fish PC from GitHub because the cost cosewic and Sara listings may have changed since the last version on your machine.

**Comment by Mateo9569** [comment]
Completed everything you mentioned except for testing the pdf build as I'm unable to print to pdf. I think it's a package problem. I'll take a look at my session info and compare to yours.

**Comment by Mateo9569** [comment]
Table looks good in pdf, fits the page

**Comment by NewGraphEnvironment** [comment]
looks like the BT population is not showing as special concern

this is from last year.  will see if can see why

**Comment by NewGraphEnvironment** [comment]
it must have come from the elk. 

`mutate(CDCode = case_when(species_code == 'BT' ~ 'F-SACO-11', ##pacific population yo`

these fish come from the arctic

https://www.sararegistry.gc.ca/virtual_sara/files/cosewic/sr_omble_tete_plat_bull_trout_1113_e.pdf
