### ISSUE TITLE
build histogram to determine life stage cutoffs, produce a graph and populate Step 2

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#9]
Also just leaving a reminder here that FWCP doesn't like ggdark graphs

**Comment by Mateo9569** [comment]
@NewGraphEnvironment do I need to do special `case_when` statements for the sculpin that we caught? The life stage cutoffs would be different compared to rainbow trout

**Comment by NewGraphEnvironment** [comment]
good question. Lets just filter those out of the histogram for analysis,  put a note in the step 2 comments that sculpin were not classified by life stage.  They are not salmonids so there are no "parr".  If we need to leave them in for the burn to the hab con file I would assume they will all land as fry... If that is the case you could add a mutate(whatever = case_when) to turn them all into adults before the paste.
