### ISSUE TITLE
125194 trib to Missinka upstream modelled crossings

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#92]
there are numerous upstream crossings modelled here but nothing mentioned in the background of the site.  we confirmed that the first crossign was not present and there are many crossings that can be xreferenced in `bcfishpass` repo as not present after review of aerial imagery.  @Mateo9569 - please add to `bcfishpass` repo. I will deal with the report text

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/assets/46538103/12bd1091-e595-4574-9442-5183e62b2ef4)

**Comment by Mateo9569** [comment]
This was done in this [PR #376](https://github.com/smnorris/bcfishpass/pull/376). Forgot to close this issue.
